project:
  type: website
  output-dir: docs

website:
  title: "Group 10: Data Science and AI/ML Job Market Analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: introduction.qmd
        text: "Project Overview"
      - href: data_cleaning.qmd
        text: "Data Preparation"
      - href: eda.qmd
        text: "Exploratory Analysis"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd
        text: "ML Methods"
      - href: nlp_methods.qmd
        text: "NLP Methods"
      - href: career_plan.qmd
        text: "Career Strategy"

execute:
  echo: true
  eval: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-fold: true

